name: 'Persist Value'
on:
  workflow_dispatch:

jobs:
  # On some job, do some stuff and persist variables meant to be re-used in other jobs
  Persisting:
    name: Compute data
    runs-on: ubuntu-22.04
    steps:
      # Do your own internal business logic...
      - name: Export one variable
        uses: UnlyEd/github-action-store-variable@v2.1.0
        with:
          # Writes "FOO" and reads "STAGE"
          variables: |
            FOO=BAR
            STAGE
